<a href="https://colab.research.google.com/github/MankotiaGit/Statistical-Foundation-of-Data-Sciences-/blob/main/SFDS_PRACTICAL_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Practical 1 (Revisiting Pandas and Numpy)                                                                                   
(1) First we  import the libraries pandas and numpy                                                                            
(2) Then we take some raw data and convert it into data frames using pandas  data frame function and then assign columns name                                                                                            
(3) Display both the data frames to check whether the data is converted correctly                                                                                                    
(4) Then convert the data frames into numpy arrays                                                                                                                                                                                                                              
(5) Find shape size and dimension of both the arrays                                                                                    
(6) Then perform the operations addition, subtraction, element wise multiplication, dot product, transpose and inverse                                                                                
(7) For inverse use try-except block because inverse is possible only when the matrix is square and non-singular                                                                         
(8) Display the results of all the operations

In [ ]:
import pandas as pd
import numpy as np

# Step 1: Take raw data and convert it into DataFrames

raw_data1 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

raw_data2 = [
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
]

df1 = pd.DataFrame(raw_data1, columns=['A', 'B', 'C'])
df2 = pd.DataFrame(raw_data2, columns=['A', 'B', 'C'])

print(" Step 1: Conversion to DataFrames ")
print("\nDataFrame 1:")
print(df1)
print("\nDataFrame 2:")
print(df2)

# Step 2: Using numpy find out: shape, size, dimension

arr1 = df1.to_numpy()
arr2 = df2.to_numpy()

print("\n Step 2: Using numpy find out: shape, size, dimension ")
print("\nArray 1:")
print(arr1)
print("Shape of arr1     :", arr1.shape)
print("Size of arr1      :", arr1.size)
print("Dimension of arr1 :", arr1.ndim)

print("\nArray 2:")
print(arr2)
print("Shape of arr2     :", arr2.shape)
print("Size of arr2      :", arr2.size)
print("Dimension of arr2 :", arr2.ndim)

# Step 3: Perform operations: addition, multiplication, subtraction, inverse, transpose, dot product

print("\n Step 3:Perform operations-addition, multiplication, subtraction, inverse, transpose, dot product ")

print("\n1. Addition (arr1 + arr2):")
print(arr1 + arr2)

print("\n2. Subtraction (arr1 - arr2):")
print(arr1 - arr2)

print("\n3. Element-wise Multiplication (arr1 * arr2):")
print(arr1 * arr2)

print("\n4. Matrix Product (Dot Product):")
print(np.dot(arr1, arr2))

print("\n5. Transpose of arr1:")
print(arr1.T)
print("\nTranspose of arr2:")
print(arr2.T)

print("\n6. Inverse:")
try:
    print("Inverse of arr1:")
    print(np.linalg.inv(arr1))
except np.linalg.LinAlgError:
    print("arr1 is singular (not invertible)")

try:
    print("\nInverse of arr2:")
    print(np.linalg.inv(arr2))
except np.linalg.LinAlgError:
    print("arr2 is singular (not invertible)")

 Step 1: Conversion to DataFrames 

DataFrame 1:
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

DataFrame 2:
   A  B  C
0  9  8  7
1  6  5  4
2  3  2  1

 Step 2: Using numpy find out: shape, size, dimension 

Array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of arr1     : (3, 3)
Size of arr1      : 9
Dimension of arr1 : 2

Array 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]
Shape of arr2     : (3, 3)
Size of arr2      : 9
Dimension of arr2 : 2

 Step 3:Perform operations-addition, multiplication, subtraction, inverse, transpose, dot product 

1. Addition (arr1 + arr2):
[[10 10 10]
 [10 10 10]
 [10 10 10]]

2. Subtraction (arr1 - arr2):
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

3. Element-wise Multiplication (arr1 * arr2):
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

4. Matrix Product (Dot Product):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

5. Transpose of arr1:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Transpose of arr2:
[[9 6 3]
 [8 5 2]
 [7 4 1]]

6. Inverse:
Inverse of arr1:
arr1 is singular (not invertible)

Inverse of arr